"use client";
import React, { useCallback, useEffect } from "react";
import { Provider, useDispatch } from "react-redux";
import BasicLayout from "@/layouts/BasicLayout";
import store, { AppDispatch } from "@/stores";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { getLoginUserUsingGet } from "@/api/userController";
import { setLoginUser } from "@/stores/loginUser";
import "./globals.css";

// import type { Metadata } from "next";
// export const metadata: Metadata = {
//   title: "亦忻面试刷题平台", // 网页标题描述
//   description: "Generated by create next app",
// };

/**
 * 全局初始化逻辑
 * @param children
 * @constructor
 */
const InitLayout: React.FC<
  Readonly<{
    children: React.ReactNode;
  }>
> = ({ children }) => {
  const disPatch = useDispatch<AppDispatch>();
  // 初始化全局用户状态
  const doInitLoginUser = useCallback(async () => {
    const res = await getLoginUserUsingGet();
    if (res.data) {
      // 更新全局用户状态
    } else {
      setTimeout(() => {
        const testuser = {
          userName: "测试登陆",
          id: 1,
          userAvatar: "https://www.code-nav.cn/logo.png",
        };
        disPatch(setLoginUser(testuser));
      }, 3000);
    }
  }, []);

  // 只执行一次
  useEffect(() => {
    doInitLoginUser();
  }, []);

  return children;
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh">
      <body>
        <AntdRegistry>
          <Provider store={store}>
            <InitLayout>
              <BasicLayout>{children}</BasicLayout>
            </InitLayout>
          </Provider>
        </AntdRegistry>
      </body>
    </html>
  );
}
